name: Create a Plugin Zip Archive and GitHub Release when a new version is tagged.

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*-*"
      - "v*.*.*"
permissions:
  contents: read

jobs:
  build:
    env:
       ZIP_NAME: "govpack.zip"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout The Repos
        uses: actions/checkout@v4

      - name: PHP Install & Build
        uses: ./.github/actions/composer

      - name: JS Install & Build
        uses: ./.github/actions/npm

      - name: Extract Git Tag Version Info (eg -rc*, -dev, -alpha)
        uses: olegtarasov/get-tag@v2.1.3
        id: tagVersion
        with:
          tagRegex: "-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
        
      - name: Extract Git Tag Version Info (eg -rc*, -dev, -alpha)
        uses: olegtarasov/get-tag@v2.1.3
        id: tag

      - name: Extracted version
        run: echo ${{steps.tagVersion.outputs.tag}}

      - name: Generate the release file for a release candidate
        run: composer generate_version --pre-release ${{ steps.tagVersion.outputs.tag }} --build ${{github.run_number}}
        if: ${{steps.tagVersion.outputs.tag != ''}}

      - name: Generate the release file for a normal release & remove the dev helper class
        run: composer generate_version --build ${{github.run_number}} && rm -f ./includes/class-dev-helpers.php
        if: ${{steps.tagVersion.outputs.tag == ''}}

      - name: Rename readme from md to txt
        run: mv README.md readme.txt

      - name: Generate WP Archive
        id: generate-archive
        uses: ./.github/actions/wp-cli-dist-archive
        with: 
          path: .
          target: ./artifacts/govpack-${{steps.tag.outputs.tag}}.zip
          plugin-dirname: "govpack"
          format: "zip"
          filename-format: "{name}.{version}"

      - name: Generate Release File name
        uses: mad9000/actions-find-and-replace-string@5
        id: release-candidate-file-name
        with:
          source: ${{steps.generate-archive.outputs.filename}}
          find: '.zip'
          replace: "-${{steps.tagVersion.outputs.tag}}.zip"
        if: ${{steps.tagVersion.outputs.tag != ''}}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ./artifacts/${{steps.release-candidate-file-name.outputs.value}}
        env: 
          GITHUB_REPOSITORY: ${{ github.repository }}

